CREATE DATABASE php_ecomproject_db;

USE php_ecomproject_db;



CREATE TABLE IF NOT EXISTS user_info(
  ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR (255),
  PASSWORD VARCHAR (255),
  FIRST_NAME VARCHAR (255),
  LAST_NAME VARCHAR (255),
  MIDDLE_NAME VARCHAR (255)
);

ALTER TABLE user_info ADD COLUMN active BOOLEAN;
